# .github/workflows/audit.yml
name: Automated SEO Audit

# 1. Define the trigger: Manual workflow dispatch
on:
  workflow_dispatch:
    inputs:
      # 🎯 TARGET URL INPUT
      audit_url:
        description: 'Target URL for the SEO audit (e.g., https://example.com)'
        required: true
        default: 
      
      # ⚙️ AUDIT LEVEL INPUT (Basic/Standard)
      audit_level:
        description: 'Select the audit level (Basic focuses on meta/H1s; Advanced adds Readability/GTM/Local SEO)'
        required: true
        default: 'standard'
        type: choice
        options:
          - basic
          - standard
          
      # 🗺️ AUDIT SCOPE INPUT (Page Limit/Crawl Depth)
      audit_scope:
        description: 'Crawl scope and depth'
        required: true
        default: 'only_onpage'
        type: choice
        options:
          - only_onpage        # Single Page Crawl (Max 1 page, Depth 1)
          - indexed_pages      # On-Page + Initial Links (Max 25 pages, Depth 2)
          - full_300_pages     # Full SEO Audit (Max 300 pages, Depth 5)
          
      # 🏆 COMPETITOR INPUT
      competitor_url:
        description: 'Optional competitor URL for analysis (Used for reference in the final report)'
        required: false

jobs:
  run_seo_audit:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      # 3. Install necessary system dependencies for Playwright
      - name: 3. Install Playwright system dependencies
        run: sudo apt-get update && sudo apt-get install -y libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libgbm-dev libxkbcommon-x11-0

      # 4. Install Python Dependencies (Success depends on the fixed requirements.txt)
      - name: 4. Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      # 5. Install Playwright browser and NLP data (Fixes the last error)
      - name: 5. Install Browsers and NLP Data
        run: |
          playwright install chromium --with-deps 
          # CRITICAL: These must run after pip install
          python -m textblob.download_corpora
          python -m nltk.downloader punkt
          
      # 6. Run SEO Audit
      - name: 6. Run SEO Audit
        # Passes the user-defined inputs as environment variables to main.py
        env:
          AUDIT_URL: ${{ github.event.inputs.audit_url }}
          AUDIT_LEVEL: ${{ github.event.inputs.audit_level }}
          AUDIT_SCOPE: ${{ github.event.inputs.audit_scope }}
          COMPETITOR_URL: ${{ github.event.inputs.competitor_url }}
        run: python main.py

      # 7. Upload SEO Audit Reports
      - name: 7. Upload SEO Audit Reports
        uses: actions/upload-artifact@v4
        with:
          name: seo-audit-reports-${{ github.event.inputs.audit_level }}-${{ github.event.inputs.audit_scope }}
          path: reports/
          if-no-files-found: warn
          
