name: Automated SEO Audit

on:
  workflow_dispatch:
    inputs:
      audit_url:
        description: 'URL to audit (e.g., https://example.com)'
        required: true
        type: string
      audit_level:
        description: 'Audit scope level (standard, advanced)'
        required: false
        default: 'standard'
        type: choice
        options:
          - standard
          - advanced
      audit_scope:
        description: 'How many pages to crawl (only_onpage, indexed_pages, full_300_pages)'
        required: false
        default: 'only_onpage'
        type: choice
        options:
          - only_onpage
          - indexed_pages
          - full_300_pages
      competitor_url:
        description: 'Optional: Competitor URL for comparison'
        required: false
        default: ''
        type: string

jobs:
  run_seo_audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # === CRITICAL STEP FOR PLAYWRIGHT STABILITY IN GITHUB ACTIONS ===
      # Installs the Linux system dependencies needed for Chromium/Playwright
      - name: Install Playwright dependencies (Required for browser rendering)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libglib2.0-0 libnss3 libfontconfig1 libcups2 libxtst6 libxss1 libgbm-dev \
            libasound2-data libasound2-plugins libpulse0 libffi-dev libx264-dev

      - name: Install Python dependencies and Playwright browser
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --upgrade
          # Installs the actual browser executable (Chromium) that Scrapy-Playwright uses
          playwright install --with-deps 
          python -m textblob.download_corpora
          python -m nltk.downloader punkt
      # ================================================================

      - name: Run SEO Audit (Handles JS pages)
        env:
          AUDIT_URL: ${{ github.event.inputs.audit_url }}
          AUDIT_LEVEL: ${{ github.event.inputs.audit_level }}
          AUDIT_SCOPE: ${{ github.event.inputs.audit_scope }}
          COMPETITOR_URL: ${{ github.event.inputs.competitor_url }}
        run: python main.py

      - name: Upload SEO Audit Reports
        uses: actions/upload-artifact@v4
        with:
          name: seo-audit-reports-${{ github.event.inputs.audit_level }}-${{ github.event.inputs.audit_scope }}
          path: reports/
          
