name: SEO Audit Workflow

# Trigger the workflow manually with input fields
on:
  workflow_dispatch:
    inputs:
      audit_url:
        description: 'URL to audit'
        required: true
        default: 'https://example.com'
      audit_level:
        description: 'Audit level (basic or standard)'
        required: true
        default: 'standard'
        type: choice
        options:
        - basic
        - standard
      competitor_url:
        description: 'Competitor URL for comparison'
        required: false
      audit_scope:
        description: 'Crawl scope'
        required: true
        default: 'only_onpage'
        type: choice
        options:
        - only_onpage
        - onpage_and_index_pages
        - full_site_250_pages

jobs:
  run-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies and corpora 🛠️
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --upgrade
          # Fix for ImportError: Downloads the necessary data for textblob
          python -m textblob.download_corpora

      - name: Run SEO Audit 🚀
        env:
          AUDIT_URL: ${{ github.event.inputs.audit_url }}
          AUDIT_LEVEL: ${{ github.event.inputs.audit_level }}
          COMPETITOR_URL: ${{ github.event.inputs.competitor_url }}
          AUDIT_SCOPE: ${{ github.event.inputs.audit_scope }}
        run: |
          python main.py

      - name: Upload SEO Audit Reports
        uses: actions/upload-artifact@v4
        with:
          name: seo-audit-reports-${{ github.event.inputs.audit_level }}
          path: reports/
          # Keeps the report for 5 days. You can adjust this value.
          retention-days: 5
