Name: SEO Audit Tool

# This workflow allows you to manually trigger the audit from the GitHub Actions tab.
on:
  workflow_dispatch:
    inputs:
      audit_url:
        description: 'URL to audit'
        required: true
        # Keep default empty or set to a safe example URL
        default:
        
      audit_level:
        description: 'Audit intensity (basic, standard)'
        required: true
        default: 'standard'
        type: choice
        options:
          - basic
          - standard
      audit_scope:
        description: 'Crawl scope (only_onpage, indexed_pages, full_300_pages)'
        required: true
        default: 'only_onpage'
        type: choice
        options:
          - only_onpage
          - indexed_pages
          - full_300_pages
      competitor_url:
        description: 'Optional: Competitor URL for comparison'
        required: false
        default: ''

jobs:
  seo_audit_job:
    # Use a standard, fast runner
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Checkout repository code
        uses: actions/checkout@v4

      - name: 2. Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      # 🚀 FIX 1: Install Python dependencies FIRST, then Playwright binaries
      - name: 3. Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      # 🚀 FIX 2: Install the Playwright browser with all its system dependencies
      - name: 4. Install Playwright browser and dependencies
        run: |
          # CRITICAL: This installs Chromium AND the required system libraries (like libnss3, libgbm-dev) 
          # on the Ubuntu runner in one consolidated step, ensuring dynamic crawling works.
          playwright install chromium --with-deps 
          python -m textblob.download_corpora
          python -m nltk.downloader punkt
          
      # ================================================================

      - name: 5. Run SEO Audit (Handles JS pages)
        # Sets the environment variables needed by main.py
        env:
          AUDIT_URL: ${{ github.event.inputs.audit_url }}
          AUDIT_LEVEL: ${{ github.event.inputs.audit_level }}
          AUDIT_SCOPE: ${{ github.event.inputs.audit_scope }}
          COMPETITOR_URL: ${{ github.event.inputs.competitor_url }}
        run: python main.py

      - name: 6. Upload SEO Audit Reports
        uses: actions/upload-artifact@v4
        with:
          # Use consistent naming for the output folder
          name: seo-audit-reports-${{ github.event.inputs.audit_level }}-${{ github.event.inputs.audit_scope }}
          path: reports/
          
