name: Automated SEO Audit

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Website URL to audit'
        required: true
        type: string

jobs:
  seo-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 markdownify

      - name: Run SEO Audit
        run: python seo_audit.py "${{ github.event.inputs.url }}"

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: seo-audit-report
          path: seo_audit_report.md
