name: On-Page SEO Audit

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Website URL for audit'
        required: true
        default: 'https://example.com'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run On-Page Audit
        run: python aggregator.py --url "${{ github.event.inputs.url }}"

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: seo-onpage-report
          path: report.pdf

      - name: Upload JSON result
        uses: actions/upload-artifact@v4
        with:
          name: seo-onpage-json
          path: result.json
