name: SEO Audit

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Enter the website URL to audit'
        required: true
        default: 'https://example.com'

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 markdown

      - name: Run SEO Audit
        run: |
          echo "Auditing ${{ github.event.inputs.url }}"
          python seo_audit.py "${{ github.event.inputs.url }}"

      - name: Generate AI Report
        run: |
          echo "Generating AI Report..."
          python report_generator.py seo_data.json

      - name: Upload Report Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: seo-audit-reports
          path: |
            seo_data.json
            seo_report.md
            seo_report.html
