---

## 🔹 4. Workflow (`.github/workflows/seo_audit.yml`)
name: SEO Audit

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Enter the website URL to audit'
        required: true
        default: 'https://example.com'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run SEO Audit
        run: python seo_audit.py "${{ github.event.inputs.url }}"

      - name: Generate Professional Report with AI
        env:
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
        run: python report_generator.py

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: seo-report
          path: seo_report.md
