---

## 📌 4. GitHub Actions Workflow (`.github/workflows/seo_audit.yml`)

```yaml
name: SEO Audit

on:
  workflow_dispatch:
    inputs:
      url:
        description: "Enter website URL"
        required: true
        default: "http://example.com"

jobs:
  seo-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run SEO Audit
        run: python seo_audit.py ${{ github.event.inputs.url }}

      - name: Generate Report
        run: python report_generator.py

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: seo-report
          path: seo_report.md
