name: SEO Audit

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Enter the website URL to audit'
        required: true
        default: 'https://example.com'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run SEO Data Collection
        run: python seo_audit.py "${{ github.event.inputs.url }}"

      - name: Generate Report
        run: python report_generator.py seo_data.json

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: seo-report
          path: seo_report.md
          
